### ISSUE TITLE
[Feature Request]: Alternative to energy

### ISSUE THREAD

**Issue by MJRamon** [terrarium-earth/Vitalize#11]
### Is your feature request related to a problem?

Not all modpacks or servers are tech oriented: many of them are fantasy/medieval based.
Thus, it would be great to have some kind of alternative to energy.

Also, 1.19.2 is still very relevant and I ask to keep supporting this version in up-to-date status.

### Solution(s)

Even as simple as coal would be enough

### Mod Version

1.19.2-1.1.1

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
I wont be adding a non energy option, the point of vitalize is *supposed* to be a tech addon for spirit.

I also won't be adding any new features to this version, it is not, as you say, up to date
